# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ed2d5b47e6241cb7f4511548473c1834b72a91ea3850ff5252bcb489e64b30734c8fd0f7ebe3fd0743a4dcea5bccdfe30ff92a766f7dff83bedd9bbedac86c4

test:
  secret_key_base: 481b22e425888134902bd870f2bd6d5ff19c21162dda148a3df30bc84608c05c22faa0a3da23d4001668a4b371b17f0c780e02a077bce3ec4565e59a969159af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
